"""MUFASA's reusable, offline entity-resolution module."""

from .adapters import MufasaInputs, load_mufasa_inputs
from .authorities import AuthoritySnapshot, load_authority_snapshot
from .contracts import (
    AlignmentStatus,
    AliasTrust,
    AssertionStatus,
    AuthorityHint,
    AuthorityLink,
    Candidate,
    CanonicalAlias,
    CanonicalEntity,
    ConceptMergePlan,
    ConstraintType,
    ContractError,
    DecisionMethod,
    DecisionStatus,
    EntityInstance,
    EntityRedirect,
    EntityRelation,
    EntityType,
    EventType,
    IdentityScope,
    InvalidMentionRecord,
    LifecycleStatus,
    Mention,
    OwnerKind,
    Proposal,
    ProposalKind,
    ProvenanceScope,
    Qualifier,
    ResolutionConflict,
    ResolutionConstraint,
    ResolutionDecision,
    ResolutionEvent,
    ResolutionRun,
)
from .evaluation import EvaluationReport, evaluate_run
from .io import (
    load_registry_snapshot,
    load_resolution_run,
    write_registry_snapshot,
    write_resolution_run,
)
from .pipeline import (
    CommitResult,
    ResolutionExecution,
    commit_resolution_run,
    preflight_capabilities,
    resolve_batch,
)
from .policy import ResolverPolicy, load_policy
from .registry import (
    RegistryChange,
    RegistrySnapshot,
    SplitPartition,
    merge_concepts,
    reassign_instance_concept,
    record_human_constraint,
    split_concept,
)

__all__ = [
    "AuthoritySnapshot",
    "AlignmentStatus",
    "AliasTrust",
    "AssertionStatus",
    "AuthorityHint",
    "AuthorityLink",
    "Candidate",
    "CanonicalAlias",
    "CanonicalEntity",
    "CommitResult",
    "ConceptMergePlan",
    "ConstraintType",
    "ContractError",
    "DecisionMethod",
    "DecisionStatus",
    "EntityInstance",
    "EntityRedirect",
    "EntityRelation",
    "EntityType",
    "EvaluationReport",
    "EventType",
    "IdentityScope",
    "InvalidMentionRecord",
    "LifecycleStatus",
    "Mention",
    "MufasaInputs",
    "RegistryChange",
    "RegistrySnapshot",
    "OwnerKind",
    "Proposal",
    "ProposalKind",
    "ProvenanceScope",
    "Qualifier",
    "ResolutionConflict",
    "ResolutionConstraint",
    "ResolutionDecision",
    "ResolutionEvent",
    "ResolutionExecution",
    "ResolutionRun",
    "ResolverPolicy",
    "SplitPartition",
    "commit_resolution_run",
    "evaluate_run",
    "load_authority_snapshot",
    "load_mufasa_inputs",
    "load_policy",
    "load_registry_snapshot",
    "load_resolution_run",
    "merge_concepts",
    "preflight_capabilities",
    "reassign_instance_concept",
    "record_human_constraint",
    "resolve_batch",
    "split_concept",
    "write_registry_snapshot",
    "write_resolution_run",
]
